site_name: PlayRTC Documents
theme: readthedocs
# theme_dir: 'custom_theme'
pages:
- Home: 'index.md'
- Hello PlayRTC! : 'hello-world.md'

- Concepts:
  - 'About': 'concepts/about.md'
  - 'Migrate 1.x to 2.x': 'concepts/migrate-1x-to-2x.md'

- Browser:
  - 'Development Environment': 'browser/dev-env.md'
  - 'Tutorial - Simple Video Chat': 'browser/simple-video-chat.md'
  - 'Microsoft Internet Explorer Support': 'browser/ie-support.md'
  - 'Migrate 1.x to 2.x': 'browser/migrate-1x-to-2x.md'
  # - 'Code Samples': 'browser/code-samples.md'

- Android:
  - 'Development Environment': 'android/dev-env.md'
  - 'Tutorial - Simple Video Chat': 'android/simple-video-chat.md'
  - 'Migrate 1.x to 2.x': 'android/migrate-1x-to-2x.md'

- iOS:
  - 'Development Environment': 'ios/dev-env.md'
  - 'Tutorial - Simple Video Chat': 'ios/simple-video-chat.md'
