site_name: PlayRTC Documents
theme: readthedocs
pages:
- [index.md, Home]
- [hello-world.md, Hello PlayRTC!]
- [about.md, About]
- [dev-env.md, Development Environment]
- [simple-video-chat.md, Tutorial - Simple Video Chat]
