site_name: PlayRTC Documents
theme: readthedocs
# theme_dir: 'custom_theme'
pages:
- Home: 'index.md'
- Hello PlayRTC! : 'hello-world.md'

- Overview:
  - 'About': 'overview/about.md'
  - 'Architecture': 'overview/architecture.md'
  - 'Project Key': 'overview/project-key.md'
  - 'Support Environment': 'overview/support-environment.md'
  - 'Feature Map': 'overview/feature-map.md'
  - 'Frequently Asked Questions': 'overview/faq.md'
  - 'Glossary': 'overview/glossary.md'
  - 'Trouble Shooting': 'overview/troubleshooting.md'
  - 'Migrate 1.x to 2.x': 'overview/migrate-1x-to-2x.md'

- Browser:
  - 'Development Environment': 'browser/dev-env.md'
  - 'Tutorial - Simple Video Chat': 'browser/simple-video-chat.md'
  - 'Microsoft Internet Explorer Support': 'browser/ie-support.md'
  - 'Migrate 1.x to 2.x': 'browser/migrate-1x-to-2x.md'

- Android:
  - 'Development Environment': 'android/dev-env.md'
  - 'Tutorial - Simple Video Chat': 'android/simple-video-chat.md'
  - 'Migrate 1.x to 2.x': 'android/migrate-1x-to-2x.md'

- iOS:
  - 'Development Environment': 'ios/dev-env.md'
  - 'Tutorial - Simple Video Chat': 'ios/simple-video-chat.md'
