site_name: PlayRTC Documents
theme: readthedocs
# theme_dir: 'custom_theme'
pages:
- ['index.md', 'Home']
- ['concepts/about.md', 'Concepts', 'About']
- ['browser/hello-world.md', 'Browser', 'Hello PlayRTC!']
- ['browser/dev-env.md', 'Browser', 'Development Environment']
- ['browser/simple-video-chat.md', 'Browser', 'Tutorial - Simple Video Chat']
